// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAN6IYuJXDrcTBakPxO91KAQieMTpwzbAs',
    appId: '1:1087215607248:web:09e5e3340c117c2b09add5',
    messagingSenderId: '1087215607248',
    projectId: 'notwhatsapp-b9525',
    authDomain: 'notwhatsapp-b9525.firebaseapp.com',
    storageBucket: 'notwhatsapp-b9525.appspot.com',
    measurementId: 'G-LNHE4Z4SEL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAObiLTe-BFTRXgYFCzAgnpieMpOLfTybI',
    appId: '1:1087215607248:android:b667a7b6fb80304909add5',
    messagingSenderId: '1087215607248',
    projectId: 'notwhatsapp-b9525',
    storageBucket: 'notwhatsapp-b9525.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA7GHIExpV79c65TkD6YaEDz0lrxCbralY',
    appId: '1:1087215607248:ios:e7f821779a5e727c09add5',
    messagingSenderId: '1087215607248',
    projectId: 'notwhatsapp-b9525',
    storageBucket: 'notwhatsapp-b9525.appspot.com',
    iosClientId: '1087215607248-h1sid5mlt7ht2ekqhd46a8vdjckdi8q6.apps.googleusercontent.com',
    iosBundleId: 'com.example.notWhatsapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA7GHIExpV79c65TkD6YaEDz0lrxCbralY',
    appId: '1:1087215607248:ios:e7f821779a5e727c09add5',
    messagingSenderId: '1087215607248',
    projectId: 'notwhatsapp-b9525',
    storageBucket: 'notwhatsapp-b9525.appspot.com',
    iosClientId: '1087215607248-h1sid5mlt7ht2ekqhd46a8vdjckdi8q6.apps.googleusercontent.com',
    iosBundleId: 'com.example.notWhatsapp',
  );
}
